### ISSUE TITLE
[2015.11.13]  重新开始写博客哈

### ISSUE THREAD

**Issue by ruandao** [ruandao/blog#1]
困死了, 一晚没睡, 折腾 `nodejs` 准备把 `es6` 学习下, 然后 `reactjs`, `react-native`  
人太迟钝了, 进程也晚别人太多, 加油 && 积累

**Comment by lymanlai** [comment]
主要是不要一直一天呆在一个地方。我现在在办公室，昨天没去冰球，结果就悲剧了。今天一定要去。去完回来效率高多了。！

**Comment by ruandao** [comment]
@lymanlai 嗯,和番茄时间一样,就是番茄时间需要预先定义好要做什么,及时进行切换,并且用5分钟的休息时间进行运动, 放松大脑

**Comment by ruandao** [comment]
@lymanlai  其实`番茄时间`不需要预定义好要做什么, 只要及时进行`5分钟的休息`,并充分放松好大脑, 这样应该也是可以试下

强制定义要充分放松大脑的时间间隔, 这样应该能够保持大块的时间块进行同一件事情
